name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    uses: bobleesj/release-scripts/.github/workflows/_build-wheel-release-publish.yml@{{ VERSION/v0 }}
    with:
      project: cifkit
