name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

jobs:
  matrix-coverage:
    uses: Billingegroup/release-scripts/.github/workflows/_matrix-and-codecov-on-merge-to-main.yml@{{ VERSION/v0 }}
    with:
      project: {{ PROJECT/PROJECT_NAME }}
      c_extension: {{ C_EXTENSION/false }}
      headless: {{ HEADLESS/false }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
