name: Build and Deploy Documentation

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  docs:
    uses: Billingegroup/release-scripts/.github/workflows/_publish-docs-on-release.yml@{{ VERSION/v0 }}
    with:
      project: {{ PROJECT/PROJECT_NAME }}
      c_extension: {{ C_EXTENSION/false }}
