name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    uses: Billingegroup/release-scripts/.github/workflows/_tests-on-pr.yml@{{ VERSION/v0 }}
    with:
      project: {{ PROJECT/PROJECT_NAME }}
      c_extension: {{ C_EXTENSION/false }}
      headless: {{ HEADLESS/false }}
