name: Tests on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests-on-pr:
    uses: Billingegroup/release-scripts/.github/workflows/_tests-on-pr.yml@{{ VERSION/v0 }}
    with:
      project: {{ PROJECT/PROJECT_NAME }}
      c_extension: {{ C_EXTENSION/false }}
      headless: {{ HEADLESS/false }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
