# Use the official Python image with a specified version
ARG PYTHON_VERSION=3.10
FROM python:${PYTHON_VERSION}-slim

# Set the working directory
WORKDIR /app

# Install necessary dependencies
RUN pip install --upgrade pip setuptools wheel twine

# Copy your package source code into the container
COPY ./ /app/

# Build the packages
RUN find /app -maxdepth 1 -type d -name 'package*' -exec python -m build {} \;

# Default command to keep the container running
CMD ["tail", "-f", "/dev/null"]
