name: Build wheel and sdist for a non-pure Python package

on:
  workflow_call:

jobs:
  build_sdist:
    name: Build diffpy.pdffit2 sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: ./dist/*.tar.gz

  build-wheels:
    needs: [build_sdist]
    defaults:
        run:
          shell: bash -l {0}

    name: cibw-wheels-${{ matrix.python[0] }}-${{ matrix.buildplat[0] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ubuntu-latest, manylinux_x86_64]
          - [macos-13, macosx_x86_64]
          - [macos-14, macosx_arm64]
          - [windows-latest, win_amd64]
        python:
          - ["3.11", "cp311"]
          - ["3.12", "cp312"]

    steps:
      - name: Check out ${{ inputs.project }}
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python[0] }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python[0] }}

      - name: Build wheels for Linux
        if: runner.os == 'Linux'
        uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_BUILD: ${{ matrix.python[1] }}-${{ matrix.buildplat[1] }}
          CIBW_BEFORE_BUILD: yum install -y gsl-devel && pip install -e .
        with:
          output-dir: dist

      - name: Build wheels for macOS
        if: runner.os == 'macOS'
        uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_BUILD: ${{ matrix.python[1] }}-${{ matrix.buildplat[1] }}
          MACOSX_DEPLOYMENT_TARGET: 13.0
          CIBW_BEFORE_BUILD: brew install gsl && pip install -e .
        with:
          output-dir: dist

      - name: Install GSL and Set Environment for GSL on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg install gsl gsl:x64-windows

      - name: Build wheels for Windows
        if: runner.os == 'Windows'
        uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_BUILD: ${{ matrix.python[1] }}-${{ matrix.buildplat[1] }}
          CIBW_ENVIRONMENT: |
            GSL_PATH=C:/vcpkg/installed/x64-windows
          CONDA_PREFIX: ${{ env.CONDA_PREFIX }}
        with:
          output-dir: dist

      - name: Upload wheels to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python[0] }}-${{ matrix.buildplat[0] }}.whl
          path: ./dist/*.whl
