name: Build Wheel, Release, Upload

on:
  workflow_call:
    inputs:
      project:
        description: 'Name of the project to build and release'
        default: 'PROJECT_NAME'
        required: false
        type: string
      c_extension:
        description: 'Whether the project has a C extension'
        default: false
        required: false
        type: boolean
      github_admin_username:
        description: 'GitHub admin authorized for GitHub/PyPI release'
        required: true
        type: string
    secrets:
      PYPI_TOKEN:
        description: 'PyPI token'
        required: true
      PAT_TOKEN:
        description: 'GitHub Personal Access Token'
        required: true

jobs:
  tag-privilege-check:
    uses: ./.github/workflows/_release_tag_privilege_check.yml
    with:
      github_admin_username: ${{ inputs.github_admin_username }}

  build-pure-python-package:
    needs: [tag-privilege-check]
    if: inputs.c_extension == false
    uses: ./.github/workflows/_build-pure-python-package.yml

  build-non-pure-python-package:
    needs: [tag-privilege-check]
    if: inputs.project == 'diffpy.pdffit2'
    uses: ./.github/workflows/_build-pdffit2-package.yml

  update-changelog:
    needs: [build-pure-python-package, build-non-pure-python-package]
    # The always() function is necessary to ensure that we wait for both build jobs to complete, even if one of them is skipped.
    # Without always(), if one of the needed jobs is skipped, the `update-changelog` job will not be executed.
    if: "always() && !contains(github.ref, 'rc')"
    runs-on: ubuntu-latest
    steps:
      - name: Fail update-changelog job if building failed
        run: |
          if [ "${{ needs.build-pure-python-package.result }}" == 'success' ] || [ "${{ needs.build-non-pure-python-package.result }}" == 'success' ]; then
            echo "Ready to update CHANGELOG.rst..."
          else
            echo "Previous build-package job failed; exiting..."
            exit 1
          fi

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update CHANGELOG.rst with the latest news
        run: |
          wget https://raw.githubusercontent.com/Billingegroup/release-scripts/v0/.github/workflows/update-changelog.py
          python update-changelog.py "${{ github.ref_name }}"
          rm update-changelog.py

      - name: Commit the changes in CHANGELOG.rst
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update changelog
          branch: main

  delete-create-new-tag:
    # For a full release, we delete and create a new tag to reflect the latest changes in the CHANGELOG.rst.
    # Recall that during the full release, the `main` branch's CHANGELOG.rst has been updated, and we want the
    # tag to reflect the latest changes in the CHANGELOG.rst done by the update-changelog above.
    # For more discussions, please read https://github.com/Billingegroup/release-scripts/pull/120
    needs: [update-changelog]
    # Always run this job for a full release but fail if the update-changelog job previously failed.
    if: "always() && !contains(github.ref, 'rc')"
    runs-on: ubuntu-latest
    steps:
      - name: Fail delete-create-new-tag job if CHANGELOG update failed
        run: |
          if [ "${{ needs.update-changelog.result }}" == 'success' ]; then
            echo "Ready to delete and create new tag containing the latest CHANGELOG.rst update in the main branch..."
          else
            echo "Previous update-changelog job failed; exiting..."
            exit 1
          fi
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Delete the tag
        run: |
          git fetch --tags
          git tag -d "${{ github.ref_name }}"
          git push origin ":${{ github.ref_name }}"
      - name: Create a new tag (Expect commit SHA to match with that of main branch)
        run: |
          git tag "${{ github.ref_name }}"
          git push origin "${{ github.ref_name }}"

  github-pre-release:
    needs: [build-pure-python-package, build-non-pure-python-package]
    if: "always() && contains(github.ref, 'rc')"
    runs-on: ubuntu-latest
    steps:
      - name: Fail github-pre-release job if building job failed
        run: |
          if [ "${{ needs.build-pure-python-package.result }}" == 'success' ] || [ "${{ needs.build-non-pure-python-package.result }}" == 'success' ]; then
            echo "Ready to pre-release on GitHub..."
          else
            echo "Previous build-package job failed; exiting..."
            exit 1
          fi

      - name: Generate GH release notes for pre-release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  github-release:
    needs: [delete-create-new-tag]
    if: "always() && !contains(github.ref, 'rc')"
    runs-on: ubuntu-latest
    steps:
      - name: Fail github-release job if CHANGELOG update failed
        run: |
          if [ "${{ needs.update-changelog.result }}" == 'success' ]; then
            echo "Ready to release on GitHub..."
          else
            echo "Previous update-changelog job failed; exiting..."
            exit 1
          fi
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Generate GH release notes for release
        run: |
          wget https://raw.githubusercontent.com/Billingegroup/release-scripts/v0/.github/workflows/get-latest-changelog.py
          python get-latest-changelog.py "${{ github.ref_name }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

  docs:
    needs: [github-pre-release, github-release]
    if: always()
    uses: ./.github/workflows/_publish-docs-on-release.yml
    with:
      project: ${{ inputs.project }}
      c_extension: ${{ inputs.c_extension }}
