name: Build and Deploy Documentation

on:
  workflow_call:
    inputs:
      project:
        description: 'Name of the project to test'
        default: 'PROJECT_NAME'
        required: false
        type: string
      c_extension:
        description: 'Whether the project has a C extension'
        default: false
        required: false
        type: boolean

jobs:
  docs:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ inputs.project }}
        uses: actions/checkout@v4

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: build
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda config
        run: >-
          conda config --set always_yes yes
          --set changeps1 no

      - name: IInstall ${{ inputs.project }} and docs requirements
        run: |
          conda install --file requirements/run.txt
          conda install --file requirements/docs.txt
          if ${{ inputs.c_extension }}; then
            conda install --file requirements/build.txt
          fi
          python -m pip install -r requirements/pip.txt
          python -m pip install . --no-deps

      - name: build documents
        run: make -C doc html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
